jobs:
  earlyaccess:
    if: github.repository == 'kordamp/bootstrapfx' && startsWith(github.event.head_commit.message,
      'Releasing version') != true
    name: EarlyAccess
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties')
          }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
        path: ~/.gradle/wrapper
        restore-keys: '${{ runner.os }}-gradlew-

          '
    - continue-on-error: true
      name: Build
      run: ./gradlew -Prelease=true build -S
    - continue-on-error: true
      id: vars
      name: Version
      run: echo ::set-output name=version::$(cat VERSION)
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        JRELEASER_PROJECT_VERSION: ${{ steps.vars.outputs.version }}
      name: Release
      uses: jreleaser/release-action@v1
      with:
        arguments: release
        version: early-access
    - continue-on-error: true
      if: always()
      name: JReleaser output
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: 'out/jreleaser/trace.log

          out/jreleaser/output.properties

          '
name: EarlyAccess
on:
  repository_dispatch:
    types: trigger-ga___early-access.yml
