jobs:
  release:
    name: Release
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties')
          }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
        path: ~/.gradle/wrapper
        restore-keys: '${{ runner.os }}-gradlew-

          '
    - continue-on-error: true
      name: Set release version
      run: 'VERSION=${{ github.event.inputs.version }}

        echo $VERSION > VERSION

        git add VERSION

        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git config --global user.name "GitHub Action"

        git commit -a -m "Releasing version $VERSION"

        git push origin main

        '
    - continue-on-error: true
      name: Build
      run: './gradlew -Prelease=true build -S

        '
    - continue-on-error: true
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      name: Deploy
      run: './gradlew -Prelease=true -Pfull-release=true \

        -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} \

        -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }} \

        build publishToSonatype -S

        '
    - continue-on-error: true
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
        JRELEASER_PROJECT_VERSION: ${{ github.event.inputs.version }}
        JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET
          }}
        JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      name: Release
      uses: jreleaser/release-action@v1
      with:
        arguments: full-release
        version: early-access
    - continue-on-error: true
      if: always()
      name: JReleaser output
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: 'out/jreleaser/trace.log

          out/jreleaser/output.properties

          '
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
